// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7iM92e0F4gnmsRs4NlFKYu6Tax7eNwoQ',
    appId: '1:938253038110:web:7a68b6f5604188ac91340f',
    messagingSenderId: '938253038110',
    projectId: 'chating-app-d6c36',
    authDomain: 'chating-app-d6c36.firebaseapp.com',
    storageBucket: 'chating-app-d6c36.appspot.com',
    measurementId: 'G-3JMBJP7JXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuJGnugGKg8F8rMymfHIqaIHHkwcbkG7c',
    appId: '1:938253038110:android:69118aa434ecf6ae91340f',
    messagingSenderId: '938253038110',
    projectId: 'chating-app-d6c36',
    storageBucket: 'chating-app-d6c36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFlcIT217Nm4F0ieyvo80Hi8N34ep0Yb0',
    appId: '1:938253038110:ios:b50d89d724e54b1791340f',
    messagingSenderId: '938253038110',
    projectId: 'chating-app-d6c36',
    storageBucket: 'chating-app-d6c36.appspot.com',
    iosClientId: '938253038110-48i8p8j35fjug0nor2mlfirnc7vmh634.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFlcIT217Nm4F0ieyvo80Hi8N34ep0Yb0',
    appId: '1:938253038110:ios:345338ce8a20bc5c91340f',
    messagingSenderId: '938253038110',
    projectId: 'chating-app-d6c36',
    storageBucket: 'chating-app-d6c36.appspot.com',
    iosClientId: '938253038110-t4oaomm0or5utm6abf4mu6lgu7hhjqtc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatingApp.RunnerTests',
  );
}
